In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../database/mutual_fund.db")

In [18]:
query = """
SELECT
    amfi_code,
    aum_crore
FROM fact_performance
ORDER BY aum_crore DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

   amfi_code  aum_crore
0     148568      49046
1     120842      47469
2     118634      43630
3     149322      41828
4     102886      41728

In [22]:
query = """

-- QUERY 1: Top 5 Funds by AUM


SELECT
    amfi_code,
    aum_crore
FROM fact_performance
ORDER BY aum_crore DESC
LIMIT 5;



"""

pd.read_sql(query, conn)

   amfi_code  aum_crore
0     148568      49046
1     120842      47469
2     118634      43630
3     149322      41828
4     102886      41728

In [25]:
query = """


-- =====================================================
-- QUERY 3: Total SIP Inflow by Year
-- =====================================================

SELECT
    strftime('%Y', month) AS year,
    SUM(sip_inflow_crore) AS total_sip_inflow
FROM fact_sip
GROUP BY year
ORDER BY year;



"""

pd.read_sql(query, conn)

   year  total_sip_inflow
0  None            939721

In [26]:
query = """


-- =====================================================
-- QUERY 4: Transactions by State
-- =====================================================

SELECT
    state,
    COUNT(*) AS total_transactions,
    SUM(amount_inr) AS total_amount
FROM fact_transactions
GROUP BY state
ORDER BY total_amount DESC;



"""

pd.read_sql(query, conn)

             state  total_transactions  total_amount
0           Punjab                2965     315780459
1       Tamil Nadu                2806     315177237
2   Madhya Pradesh                2931     308312493
3        Rajasthan                2577     298645822
4          Gujarat                2780     298358940
5      West Bengal                2748     297182514
6        Telangana                2718     290219284
7            Delhi                2677     289633404
8    Uttar Pradesh                2695     285368873
9          Haryana                2736     279634354
10       Karnataka                2621     273753570
11     Maharashtra                2524     269513480

In [27]:
query = """



-- =====================================================
-- QUERY 5: Funds with Expense Ratio Below 1%
-- =====================================================

SELECT
    scheme_name,
    fund_house,
    expense_ratio_pct
FROM dim_fund
WHERE expense_ratio_pct < 1
ORDER BY expense_ratio_pct;



"""

pd.read_sql(query, conn)

,scheme_name,fund_house,expense_ratio_pct
0,Nippon India Gilt Securities Fund - Regular - ...,Nippon India MF,0.55
1,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,0.56
2,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,0.60
3,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,0.66
4,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,0.72
5,Nippon India Large Cap Fund - Direct - Growth,Nippon India MF,0.72
6,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,0.74
7,Axis Bluechip Fund - Direct - Growth,Axis Mutual Fund,0.75
8,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,0.77
9,HDFC Mid-Cap Opportunities Fund - Direct - Growth,HDFC Mutual Fund,0.78
10,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,0.79
11,ICICI Pru Bluechip Fund - Direct - Growth,ICICI Prudential MF,0.80
12,Nippon India ETF Nifty 50 BeES,Nippon India MF,0.89
13,HDFC Top 100 Fund - Direct Plan - Growth,HDFC Mutual Fund,0.92

In [28]:
query = """



-- =====================================================
-- QUERY 6: Top 10 Fund Houses by AUM
-- =====================================================

SELECT
    fund_house,
    MAX(aum_crore) AS latest_aum
FROM fact_aum
GROUP BY fund_house
ORDER BY latest_aum DESC
LIMIT 10;





"""

pd.read_sql(query, conn)

                 fund_house  latest_aum
0           SBI Mutual Fund     1250000
1       ICICI Prudential MF     1074000
2          HDFC Mutual Fund      930000
3           Nippon India MF      700000
4         Kotak Mahindra MF      580000
5  Aditya Birla Sun Life MF      460000
6           UTI Mutual Fund      410000
7          Axis Mutual Fund      350000
8            Mirae Asset MF      290000
9           DSP Mutual Fund      230000

In [29]:
query = """


-- =====================================================
-- QUERY 7: Average Transaction Amount by Type
-- =====================================================

SELECT
    transaction_type,
    ROUND(AVG(amount_inr),2) AS avg_amount
FROM fact_transactions
GROUP BY transaction_type;



"""

pd.read_sql(query, conn)

  transaction_type  avg_amount
0          Lumpsum   254456.02
1       Redemption   250558.79
2              SIP    11018.13

In [30]:
query = """




-- =====================================================
-- QUERY 8: Top Performing Funds by Sharpe Ratio
-- =====================================================

SELECT
    d.scheme_name,
    p.sharpe_ratio
FROM fact_performance p
JOIN dim_fund d
ON p.amfi_code = d.amfi_code
ORDER BY p.sharpe_ratio DESC
LIMIT 10;



"""

pd.read_sql(query, conn)

                                         scheme_name  sharpe_ratio
0           ICICI Pru Liquid Fund - Regular - Growth          7.68
1               Kotak Liquid Fund - Regular - Growth          6.18
2                ABSL Liquid Fund - Regular - Growth          5.14
3       HDFC Short Term Debt Fund - Regular - Growth          1.84
4       SBI Magnum Gilt Fund - Regular Plan - Growth          1.52
5  Nippon India Gilt Securities Fund - Regular - ...          1.33
6          HDFC Top 100 Fund - Regular Plan - Growth          1.06
7      Mirae Asset Large Cap Fund - Regular - Growth          1.06
8          ICICI Pru Bluechip Fund - Direct - Growth          1.03
9     Nippon India Large Cap Fund - Regular - Growth          1.00

In [31]:
query = """



-- =====================================================
-- QUERY 9: Investor Distribution by Age Group
-- =====================================================

SELECT
    age_group,
    COUNT(DISTINCT investor_id) AS investors
FROM fact_transactions
GROUP BY age_group
ORDER BY investors DESC;



"""

pd.read_sql(query, conn)

  age_group  investors
0     26-35       2033
1     36-45       1237
2     18-25        753
3     46-55        589
4       56+        388

In [32]:
query = """



-- =====================================================
-- QUERY 10: Benchmark Index Performance
-- =====================================================

SELECT
    index_name,
    ROUND(MIN(close_value),2) AS min_value,
    ROUND(MAX(close_value),2) AS max_value,
    ROUND(AVG(close_value),2) AS avg_value
FROM fact_benchmark
GROUP BY index_name
ORDER BY avg_value DESC;


"""

pd.read_sql(query, conn)

        index_name  min_value  max_value  avg_value
0     BSE_SMALLCAP   23592.64   79075.39   39375.03
1         NIFTY500   14426.04   38418.87   23316.83
2          NIFTY50   17492.79   27798.72   22089.36
3  NIFTY_MIDCAP150    8980.60   32990.66   22076.53
4         NIFTY100   14128.86   21088.58   17186.44
5    CRISIL_LIQUID    2281.51    3046.00    2639.93
6      CRISIL_GILT    1444.13    2302.79    1779.53

In [33]:
query = """

-- Top 5 States by Investment Amount

SELECT
    state,
    SUM(amount_inr) AS total_investment
FROM fact_transactions
GROUP BY state
ORDER BY total_investment DESC
LIMIT 5;

"""

pd.read_sql(query, conn)

            state  total_investment
0          Punjab         315780459
1      Tamil Nadu         315177237
2  Madhya Pradesh         308312493
3       Rajasthan         298645822
4         Gujarat         298358940

In [34]:
query = """

-- SIP vs Lumpsum vs Redemption

SELECT
    transaction_type,
    COUNT(*) AS transaction_count,
    SUM(amount_inr) AS total_amount
FROM fact_transactions
GROUP BY transaction_type;

"""

pd.read_sql(query, conn)

  transaction_type  transaction_count  total_amount
0          Lumpsum               8095    2059821448
1       Redemption               4967    1244525491
2              SIP              19716     217233491